### ISSUE TITLE
The Embedded Rust Book和訳版へのリンクを追加する

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/rust-lang-ja.github.io#2]
https://tomo-wait-for-it-yuki.hatenablog.com/entry/2019/01/03/214727

**Comment by tomoyuki-nakabayashi** [comment]
お世話になります。和訳を進めている者です。
The Embedded Rust BookとDiscoveryの翻訳が一通り完了していますので、リンクに追加して頂けると、嬉しいです。

## The Embedded Rust Book

https://tomoyuki-nakabayashi.github.io/book/

repository:
https://github.com/tomoyuki-nakabayashi/book

## Discovery

https://tomoyuki-nakabayashi.github.io/discovery/

repository:
https://github.com/tomoyuki-nakabayashi/discovery

よろしくお願いいたします。
